---
#PLUGIN BY BALIGAMERZ
#IG: madeuntung_12
#Channel: https://www.youtube.com/channel/UChdUR0nmBfEhV2mWH-B2lew
#Kalau mau bertanya" Bisa DM ig
#JANGAJ DIJUAL KECUALI PEMBUAT ASLI !

#TEXT DIBATAS BAR
head: "  §bThanh nước"

#TEXT DIBAWAH BAR
sub: ""

#CEPET LAMANYA BAR  DEFAULT 1000
speed: 1000

#KECEPETAN DALAM MINUM PER BOTTLE DEFAULT 200
minum: 100
...
